In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# Clasification des sons selon leurs compositeurs

Nous avons un total de 120 sons classiques de 4 différents compositeurs (beethoven, mozart, chopin et liszt). Nous allons tenter de classifier ces sons. Nous avons crée 2 fichiers csv : chromas_clasical_sound.csv et mfccs_clasical_sound.csv grâce au fichier data_process.py, où à partir des fichiers .wav de chaque musique nous avons :
* charger la représentation chroma (respectivement mcff)
* ce qui nous a donné pour chaque extrait une matrice 12 * 2584 (chroma) et 20 * 2584 (mcff), certains morceaux etaient moins longs que les autres (moins de 2584), nous avons donc complété avec des 0 ces données pour que tous soient de longueur 2584 
* on a obtenu une matrice de chromas de taille (120 * 12 * 2584), et une matrice de mcff de taille (120 * 20 * 2584)
* nous avons vectoriser les 2 matrice pour obtenir un vecteur pour chaque sons
* on a enregistré cela dans 2 fichiers csv (un pour la représentation chroma, l'autre pour la représentation mccf) en accolant la classe du compositeurs à la fin pour chaque son.

Il ne nous reste plus qu'à charger les données et tester des classifieurs pour les deux représentations.

In [2]:
clasical_chromas = pd.read_csv("./data/clasical_sound/chromas_clasical_sound.csv")
clasical_mccfs = pd.read_csv("./data/clasical_sound/mfccs_clasical_sound.csv")

# correspondance des indices avec leurs compositeurs
composithors = ["beethoven", "chopin", "liszt", "mozart"] 

### Chromas

In [3]:
chromas = np.array(clasical_chromas)
X_chromas = chromas[:,:-1]
y_chromas = chromas[:,-1]  # la dernière colonne est la classe (le compositeurs)

X_train, X_test, y_train, y_test = train_test_split(X_chromas, y_chromas, test_size=0.3, shuffle=True)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(84, 31009) (84,)
(36, 31009) (36,)


In [4]:
from sklearn.svm import SVC

svm = SVC()
svm.fit(X_train,y_train)
print("SVM avec noyau gaussien")
print("Scores:", svm.score(X_test, y_test))
y_svm = svm.predict(X_test)
wrong_pred_svm = np.where(y_test != y_svm)
print(wrong_pred_svm)

SVM avec noyau gaussien
Scores: 0.9166666666666666
(array([15, 26, 34]),)


In [5]:
from sklearn.linear_model import LogisticRegression

reg = LogisticRegression(max_iter=200,solver='liblinear')
reg.fit(X_train,y_train)
print("Régression Logistique")
print("Scores:", reg.score(X_test, y_test))
y_reg = reg.predict(X_test)
wrong_pred_reg = np.where(y_test != y_reg)
print(wrong_pred_reg)

Régression Logistique
Scores: 0.75
(array([ 4,  6,  8, 15, 26, 29, 33, 34, 35]),)


### Mccf

In [6]:
mcffs = np.array(clasical_mccfs)
X_mcffs = mcffs[:,:-1]
y_mcffs = mcffs[:,-1]  # la dernière colonne est la classe (le compositeur)

X_train2, X_test2, y_train2, y_test2 = train_test_split(X_mcffs, y_mcffs, test_size=0.3, shuffle=True)
print(X_train2.shape, y_train2.shape)
print(X_test2.shape, y_test2.shape)

(84, 31009) (84,)
(36, 31009) (36,)


In [7]:
svm2 = SVC()
svm2.fit(X_train2,y_train2)
print("SVM avec noyau gaussien")
print("Scores:", svm2.score(X_test2, y_test2))
y_svm2 = svm.predict(X_test2)
wrong_pred_svm2 = np.where(y_test2 != y_svm2)
print(wrong_pred_svm2)

SVM avec noyau gaussien
Scores: 0.9444444444444444
(array([22, 31]),)


In [8]:
reg2 = LogisticRegression(max_iter=200,solver='liblinear')
reg2.fit(X_train2,y_train2)
print("Régression Logistique")
print("Scores:", reg2.score(X_test2, y_test2))
y_reg2 = reg2.predict(X_test2)
wrong_pred_reg2 = np.where(y_test2 != y_reg2)
print(wrong_pred_reg2)

Régression Logistique
Scores: 0.8888888888888888
(array([ 7, 21, 22, 26]),)
